title: PaleOrdia
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the PaleOrdia Lexeme and Script acessing page. 
collections:
  pages:
    output: true
    permalink: /:path/

